openapi: 3.0.0

info:
  title: API
  version: 1.0.0

servers:
  - url: http://localhost:3030/api/v1
  - url: https://arnb-backend.onrender.com/api/v1

tags:
  - name: auth
    description: Authentication
  - name: apartments
    description: Apartment management
  - name: bookings
    description: Booking system
  - name: apartment-images
    description: Images for apartments

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:

  # 🔐 AUTH
  /auth/admin/login:
    $ref: "./auth.yaml#/paths/~1auth~1admin~1login"

  /auth/refresh:
    $ref: "./auth.yaml#/paths/~1auth~1refresh"

  /auth/logout:
    $ref: "./auth.yaml#/paths/~1auth~1logout"
  
  /auth/me:
    $ref: "./auth.yaml#/paths/~1auth~1me"

  # 🏠 APARTMENTS
  /apartments:
    $ref: "./apartments.yaml#/paths/~1apartments"

  /apartments/available:
    $ref: "./apartments.yaml#/paths/~1apartments~1available"

  /apartments/search:
    $ref: "./apartments.yaml#/paths/~1apartments~1search"

  /apartments/{id}:
    $ref: "./apartments.yaml#/paths/~1apartments~1{id}"

  /apartments/{id}/cover:
    $ref: "./apartments.yaml#/paths/~1apartments~1{id}~1cover"
  
  /apartments/{id}/images:
    $ref: "./apartments.yaml#/paths/~1apartments~1{id}~1images"

  /apartments/{id}/pricing:
    $ref: "./apartments.yaml#/paths/~1apartments~1{id}~1pricing"

  /apartments/{id}/bookings/unavailable-dates:
    $ref: "./apartments.yaml#/paths/~1apartments~1{id}~1bookings~1unavailable-dates"

  /apartment-images/{id}:
    $ref: "./apartment-images.yaml#/paths/~1apartment-images~1{id}"

  # 📅 BOOKINGS
  /bookings:
    $ref: "./bookings.yaml#/paths/~1bookings"
  
  /bookings/{id}/status:
    $ref: "./bookings.yaml#/paths/~1bookings~1{id}~1status"

  /bookings/{id}:
    $ref: "./bookings.yaml#/paths/~1bookings~1{id}"

  /bookings/apartment/{id}:
    $ref: "./bookings.yaml#/paths/~1bookings~1apartment~1{id}"


  /bookings/blocked:
    $ref: "./bookings.yaml#/paths/~1bookings~1blocked"

  # 🖼️ IMAGES
  /apartment-images:
    $ref: "./apartment-images.yaml#/paths/~1apartment-images"
  
  /apartment-images/upload:
    $ref: "./apartment-images.yaml#/paths/~1apartment-images~1upload"
