openapi: 3.0.0

info:
  title: API
  version: 1.0.0

servers:
  - url: http://localhost:3030/api/v1
  - url: https://arnb-backend.onrender.com/api/v1

tags:
  - name: auth
    description: Authentication
  - name: apartments
    description: Apartment management
  - name: bookings
    description: Booking system
  - name: apartment-images
    description: Images for apartments

security:
  - cookieAuth: []

components:
  $ref: "./components/index.yaml"

paths:
  $ref: "./paths/index.yaml"